site_name: My Space
theme:
  name: 'material'
  palette:
    primary: deep purple
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
- 主页: index.md
- 知识库:
    - sql: documents/sql.md
    - 排序算法: documents/algorithm.md
    - 数据结构: documents/datastructure.md
    - 计算机网络: documents/network.md
    - leetcode: documents/leetcode.md
- 备忘录:
    - 一些喜欢的时刻: memo/share.md
    - 26.0 记: memo/26.0.md

